### ISSUE TITLE
Fullscreen mode has tabs

### ISSUE THREAD

**Issue by quozl** [sugarlabs/terminal-activity#25]
Reproducer: with only one tab, press the fullscreen button.

Observed result: notebook tab titles and add tab button is visible.  Add tab button cannot be hit because mouse movement places fullscreen cancel button over the top.

Expected result: no tab titles or tab button; switching tabs should require leaving fullscreen or using keyboard shortcuts.

![screenshot_ubuntu-xenial_2018-02-13_08 00 50](https://user-images.githubusercontent.com/2936481/36119518-41a7f75e-1094-11e8-8c7d-6c5f2405e344.png)

**Comment by yashagrawal3** [comment]
Spent a fair bit amount of time on it. Fixed using a Hack, which, i feel, is not a great way to fix this issue. @quozl do you have anyidea which function is called or what happens when fullscreen cancel button is pressed.

**Comment by quozl** [comment]
@yashagrawal3, some of the fullscreen infrastructure is in sugar-toolkit-gtk3, so have a hunt around there and the documentation at https://developer.sugarlabs.org/sugar3
