### ISSUE TITLE
Feature: URL open in Browse

### ISSUE THREAD

**Issue by quozl** [sugarlabs/terminal-activity#27]
At the moment, a URL displayed by an application has to be copied and pasted into Browse.

Example;

```
$ jupyter notebook --no-browser
    http://loocalhost:8888/?token=foo
$ █
```

* [x] research how GNOME Terminal and other Terminal emulators support URLs displayed,
 * URLs are displayed without any change,
 * URLs obscured by <kbd>OSC 8</kbd> escape sequence show the link text,
 * mouse-over underlines the URL or the link text and changes mouse cursor from vertical insertion to pointing finger,
 * clicking on the link does nothing,
 * <kbd>ctrl</kbd>-clicking on the link launches browser,
 * right-click on link shows menu with "Open Link" and "Copy Link" options for URLs, and "Open Hyperlink" and "Copy Hyperlink" options for link text,
 * implementation is in [terminal-screen.c](https://github.com/GNOME/gnome-terminal/blob/master/src/terminal-screen.c)
* [ ] design the user experience, and work to consensus,
 * URLs are to be displayed without any change,
 * URLs obscured by <kbd>OSC 8</kbd> escape sequence are to show the link text in the Terminal, and the URL when the mouse cursor hovers over the link,
 * mouse-over is to underline the URL or the link text and change mouse cursor from vertical insertion to pointing finger,
 * clicking on the link is to do nothing,
 * <kbd>ctrl</kbd>-clicking on the link is to launch Browse to display the URL,
 * right-click on link is to show a menu with "Open Link" and "Copy Link" options for URLs, and "Open Hyperlink" and "Copy Hyperlink" options for link text,
* [ ] implement similar handling in Sugar Terminal.

_(i'm not posting this issue in order to take responsibility, but rather to invite others to look at the problem)_

**Comment by quozl** [comment]
@pro-panda, @chimosky, @walterbender, @aniket21mathur, @hrishi1999; please review above and comment on what URL behaviours of GNOME Terminal should be used by Sugar Terminal?

**Comment by Hrishi1999** [comment]
The behaviors mentioned above covers all the URL behaviors in the GNOME terminal as far as I know. This much will be enough.

**Comment by chimosky** [comment]
> @pro-panda, @chimosky, @walterbender, @Aniket21mathur, @Hrishi1999; please review above and comment on what URL behaviours of GNOME Terminal should be used by Sugar Terminal?

I agree with the behaviours listed above.

**Comment by nswarup14** [comment]
Adding to the user experience checklist:-
Are multiple Journal Instances a welcome side effect of the feature? (`ctrl`+click creates a new Journal instance every time).

Thanks.

**Comment by chimosky** [comment]
> Are multiple Journal Instances a welcome side effect of the feature? (`ctrl`+click creates a new Journal instance every time).

It'll be better if it uses an existing instance and just open a new tab for the link, but if there aren't any existing instances then create a new one.

**Comment by nswarup14** [comment]
@chimosky Thanks
I agree with the same. Will work on such an implementation.

**Comment by pro-panda** [comment]
> @pro-panda, @chimosky, @walterbender, @Aniket21mathur, @Hrishi1999; please review above and comment on what URL behaviours of GNOME Terminal should be used by Sugar Terminal?

I approve

**Comment by quozl** [comment]
Thanks.  Opening comment edited accordingly.

I agree with @nswarup14 that an outstanding question is whether multiple journal _objects_ should be created, one for each click.  I'm not sure @chimosky understood that though, as you can't open a new tab on a journal _object_, so perhaps there is confusion as to what is being asked.  Journal _object_ or activity _instance_ arising from launching the _object_?

**Comment by srevinsaju** [comment]
I agree with the same as mentioned by @quozl , but on Right Click, I would like to use only Open Link, as it might be difficult to make a user differentiate between hyperlink and URL as they many stuff in common. I prefer creating a journal object each time the URL is clicked so that a student can keep a track of what he has done and what items he has launched from the Terminal Activity in sequence.

**Comment by quozl** [comment]
Thanks.  My wording was taken from the GNOME Terminal app; a hyperlink is text that links to a URL, and a URL alone has no hyperlink text.  I'm also not sure if a student could appreciate the difference, or if it is worth being exact, so I'm fine with diverging from GNOME Terminal.
