### ISSUE TITLE
Feature: erase scroll buffer

### ISSUE THREAD

**Issue by quozl** [sugarlabs/terminal-activity#32]
While using Terminal, I needed to erase the scroll buffer, but there was no button to do it.  Workaround was to stop Terminal and start a new instance.  An erase button could go in the edit menubar.

**Comment by Hrishi1999** [comment]
Do you mean a functionality similar to the "clear" command?

**Comment by quozl** [comment]
@Hrishi1999, you forgot to add "Fixes" to your pull request or commit.
