### ISSUE TITLE
Running sugar-activity3 on this activity results in error

### ISSUE THREAD

**Issue by nswarup14** [sugarlabs/terminal-activity#36]
**Tested on Ubtuntu 18.04, Sugar v0.114 built via native method.**

**Issue**
On running `sugar-activity3` to run the activity in GNOME Terminal in an "Ubuntu" setup, with Sugar v0.114 installed, the following error comes.
`ModuleNotFoundError: No module named 'ConfigParser'`

The activity runs fine with the `sugar-activity` command and as expected.
Thanks!

**Comment by quozl** [comment]
Thanks.  Error is expected.  Cause is running the Python 2 source code in _master_ branch using the Python 3 wrapper `sugar-activity3`.  The _master_ branch is currently Python 2 only.  Instead, use the source code in https://github.com/sugarlabs/terminal-activity/pull/29, and comment on that pull request.
