### ISSUE TITLE
AttributeError: 'TerminalActivity' object has no attribute '_notebook'

### ISSUE THREAD

**Issue by Saumya-Mishra9129** [sugarlabs/terminal-activity#39]
```log
File "usr/share/sugar/activities/terminal-activity/terminal.py", line 201, in bg_color_notify_cb 
    self._update_theme()
File "usr/share/sugar/activities/terminal-activity/terminal.py", line 236, in _update_theme
    for i in range(self._notebook.get_n_pages()):
AttributeError: 'TerminalActivity' object has no attribute '_notebook'   
```

**Comment by Aniket21mathur** [comment]
hiii @Saumya-Mishra9129. It will be great if you also add how to reproduce this error.

**Comment by quozl** [comment]
Starting the activity as at 1b5a10e3a75b21687e95a421dbefdd94f5797a06 (_master_) reproduces the error.

**Comment by quozl** [comment]
Still happens as at 3448586e1ce051879c24f1ec14679a0e76b87f62.

**Comment by Saumya-Mishra9129** [comment]
> Still happens as at 3448586.

Yeah maybe this regression is produced at the time of Porting.

**Comment by quozl** [comment]
@Saumya-Mishra9129.  Yes, good speculation, and reasonable assumption.  You can test by checking out commitss one by one until you find the cause.  Read up on `git bisect`, as it reduces "one by one" to roughly log to the base 2 commits.  https://github.com/sugarlabs/terminal-activity/pull/42 is said to be fix, please check if you get a chance.
